### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by mamarasulovs** [yzyouzhang/Empirical-Channel-CM#3]
Hi, thank you for the awesome project. I am facing the package installation. Could you provide a requirements.txt file based on this project?

**Comment by yzyouzhang** [comment]
I don't have that on my computer currently probably since it is a relatively old project. I believe it is close to the environment we used in a close project here: [https://github.com/yzyouzhang/HBAS_chapter_voice3](https://github.com/yzyouzhang/HBAS_chapter_voice3). Please check the requirements.txt file there. Thanks.
